export enum ContentType {
  JSON = "application/json",
  TEXT = "text/plain",
  HTML = "text/html",
  XML = "application/xml",
  FORM = "application/x-www-form-urlencoded",
  MULTIPART = "multipart/form-data",
  PDF = "application/pdf",
  CSV = "text/csv",
  STREAM = "application/octet-stream",
  IMAGE_JPEG = "image/jpeg",
  IMAGE_PNG = "image/png",
  IMAGE_GIF = "image/gif",
  IMAGE_WEBP = "image/webp",
  IMAGE_SVG = "image/svg+xml",
  AUDIO = "audio/mpeg",
  AUDIO_WAV = "audio/wav",
  AUDIO_OGG = "audio/ogg",
  VIDEO = "video/mp4",
  VIDEO_WEBM = "video/webm",
  VIDEO_OGG = "video/ogg",
  ZIP = "application/zip",
  JAVASCRIPT = "application/javascript",
  CSS = "text/css",
  YAML = "application/yaml",
  MARKDOWN = "text/markdown"
}